version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=kingsley
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data